import React from "react";
import { motion } from "framer-motion";
import { getVideosByCategory } from "../data/videos";

const PortfolioGrid = ({ category, onVideoClick }) => {
  const videos = getVideosByCategory(category);

  if (!videos || videos.length === 0) {
    return (
      <div className="portfolio-grid">
        <div style={{ 
          padding: "2rem", 
          textAlign: "center",
          color: "var(--text-muted)",
          gridColumn: "1 / -1"
        }}>
          No videos available for this category yet.
        </div>
      </div>
    );
  }

  return (
    <div className="portfolio-grid">
      {videos.map((video, index) => {
        // Check if using Mux or local video
        const isLocalVideo = video.src && !video.playbackId;
        
        // Mux thumbnail URL - automatically generated by Mux
        const muxThumbnailUrl = video.playbackId && !video.playbackId.startsWith("YOUR_MUX_PLAYBACK_ID")
          ? `https://image.mux.com/${video.playbackId}/thumbnail.jpg?width=640&height=360&fit_mode=smartcrop&time=0`
          : null;
        
        // Use custom thumbnail, Mux thumbnail, or fallback
        const thumbnailUrl = video.thumbnail || muxThumbnailUrl;

        return (
          <motion.div
            key={video.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: index * 0.05 }}
            className={`portfolio-item ${index === 0 ? 'large' : index <= 2 ? 'medium' : 'small'}`}
            onClick={() => onVideoClick(video)}
          >
            <div className="item-container">
              <div className="item-thumbnail">
                {thumbnailUrl ? (
                  <img 
                    src={thumbnailUrl} 
                    alt={video.title}
                    loading="lazy"
                    style={{
                      width: "100%",
                      height: "100%",
                      objectFit: "cover"
                    }}
                    onError={(e) => {
                      // Fallback to gradient if thumbnail fails to load
                      e.target.style.display = "none";
                    }}
                  />
                ) : (
                  <div style={{
                    width: "100%",
                    height: "100%",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    fontSize: "2rem",
                    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
                  }}>
                    🎬
                  </div>
                )}
                <div className="play-overlay">
                  <span className="play-icon">▶️</span>
                </div>
              </div>
              <div className="item-info">
                <h4 className="item-title">{video.title}</h4>
                <span className="item-duration">{video.duration}</span>
              </div>
            </div>
          </motion.div>
        );
      })}
    </div>
  );
};

export default PortfolioGrid; 